version: '3.8'

services:
  ollama:
    image: ollama/ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: >
      sh -c "
      ollama pull miqu-1-70b.q5_K_M &&
      ollama run miqu-1-70b.q5_K_M
      "

  private-gpt-api:
    build: .
    ports:
      - "8080:5000"
    volumes:
      - ./source_documents:/app/source_documents
    environment:
      - MODEL=miqu-1-70b.q5_K_M
    command: >
      conda run --no-capture-output -n private sh -c "
      python ingest.py &&
      MODEL=miqu-1-70b.q5_K_M python privateGPTAPI.py
      "

volumes:
  ollama:
